export const BlockBusterArray = [
  {
    to: "/Oneplus11R",
    title: "Oneplus 11R",
    offer: "Upto 24% offer",
    type: "Great Freedom Sale",
    price: "39,999",
    path: require("../../src/components/assests/BlockbusterArray/Oneplus 11R.jpg"),
  },
  {
    to: "/GoproHero8",
    title: "Gopro Hero 10",
    offer: "Upto 23% offer",
    type: "Great Freedom Sale",
    price: "34.989",
    path: require("../../src/components/assests/BlockbusterArray/Gopro Hero8.jpg"),
  },
  {
    to: "/JBL",
    title: "JBL Speaker",
    offer: "Upto 33% offer",
    type: "Great Freedom Sale",
    price: "6,479",
    path: require("../../src/components/assests/BlockbusterArray/JBLSpeaker.jpg"),
  },
  {
    to: "/OneplusNordBuds",
    title: "Oneplus Nord buds",
    offer: "Upto 29% offer",
    type: "Great Freedom Sale",
    price: "2,799",
    path: require("../../src/components/assests/BlockbusterArray/OneplusNordBuds.jpg"),
  },
  {
    to: "/S23Ultra",
    title: "Samsung S23 Ultra",
    offer: "Upto 27% offer",
    type: "Great Freedom Sale",
    price: "1,43,999",
    path: require("../../src/components/assests/BlockbusterArray/S23Ultra.jpg"),
  },
  {
    to: "/Keyboards",
    title: "Apple magic Wireless Keyboard",
    offer: "Upto 16% offer",
    type: "Great Freedom Sale",
    price: "14,989",
    path: require("../../src/components/assests/BlockbusterArray/Keyboards.jpg"),
  },
  {
    to: "/Alexa",
    title: "Alexa",
    offer: "Upto 41% offer",
    type: "Great Freedom Sale",
    price: "1,949",
    path: require("../../src/components/assests/BlockbusterArray/Alexa.jpg"),
  },
  {
    to: "/Cycle",
    title: "CARDIAC Cycle",
    offer: "Upto 28% offer",
    type: "Great Freedom Sale",
    price: "17,999",
    path: require("../../src/components/assests/BlockbusterArray/Cycle.jpg"),
  },
  {
    to: "/SamsungS23",
    title: "Samsung S23",
    offer: "Upto 42% offer",
    type: "Great Freedom Sale",
    price: "79,999",
    path: require("../../src/components/assests/BlockbusterArray/Samsung S23.jpg"),
  },
  {
    to: "/PS5",
    title: "Play Station 5",
    offer: "Upto 27% offer",
    type: "Great Freedom Sale",
    price: "54,990",
    path: require("../../src/components/assests/BlockbusterArray/PS5.jpg"),
  },
  {
    to: "/IQooZ7s",
    title: "IQoo Z7s",
    offer: "Upto 17% offer",
    type: "Great Freedom Sale",
    price: "21,999",
    path: require("../../src/components/assests/BlockbusterArray/IQooZ7s.jpg"),
  },
];
